# TRMNLP configuration
---
# auto-reload when files change
watch:
  - src
  - .trmnlp.yml

# values of custom fields
# This is the "proper" place.
# It works as {{resource_type}} in settings.yml
# AND maps to trmnl.plugin_settings.custom_fields_values.resource_type in Liquid.

# override variables for development
variables:
  trmnl: {}
